/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLibraryRouteImport } from './routes/api.library'
import { Route as ApiV1ItemsRouteImport } from './routes/api.v1.items'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryRoute = ApiLibraryRouteImport.update({
  id: '/api/library',
  path: '/api/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ItemsRoute = ApiV1ItemsRouteImport.update({
  id: '/api/v1/items',
  path: '/api/v1/items',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/library': typeof ApiLibraryRoute
  '/api/v1/items': typeof ApiV1ItemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/library': typeof ApiLibraryRoute
  '/api/v1/items': typeof ApiV1ItemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/library': typeof ApiLibraryRoute
  '/api/v1/items': typeof ApiV1ItemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/library' | '/api/v1/items'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/library' | '/api/v1/items'
  id: '__root__' | '/' | '/api/library' | '/api/v1/items'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLibraryRoute: typeof ApiLibraryRoute
  ApiV1ItemsRoute: typeof ApiV1ItemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library': {
      id: '/api/library'
      path: '/api/library'
      fullPath: '/api/library'
      preLoaderRoute: typeof ApiLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/items': {
      id: '/api/v1/items'
      path: '/api/v1/items'
      fullPath: '/api/v1/items'
      preLoaderRoute: typeof ApiV1ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLibraryRoute: ApiLibraryRoute,
  ApiV1ItemsRoute: ApiV1ItemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
